### PR TITLE
kmcmultiple: also output mobilities for X and Y directions

### PR DESCRIPTION
**Pull request by razziel89**
So far, kmcmultiple only outputs mobilities for the z direction. This pull request would add code to also add the same information for x and y directions if applicable.

### CODE REVIEW

**Comment by junghans** [comment]
Btw, it seems your email in not linked up to your github account:
https://help.github.com/articles/adding-an-email-address-to-your-github-account/

**Comment by razziel89** [comment]
Thanks for the information! I usually don't use the email address for github that I used on the forum, but I added it anyway.

**Comment by junghans** [comment]
@JensWehner : please review!

**Review by JensWehner — COMMENTED** [review]
The code implements the functionality described. 

I am not a fan of commenting out code and the whole thing could be much shorter using the vec class or even calculating the mobility tensor. Additionally it should go into a separate function. Considering the fact, that this class is not exactly well written and should be refactored anyway , I do not mind the merge.

**Comment by razziel89** [comment]
I agree @JensWehner. I'll make another commit today that should remedy some of your concerns.

**Pull request merged**
